### ISSUE TITLE
Documenting Testing: Manual Tests

### ISSUE THREAD

**Issue by sofireSophia** [ECU-CSCI-4230/TeamGiratina#32]
If you have any manual tests, you need to document the test scripts for each of these tests. You should start by creating a Wiki page that will list all the test script pages, and will describe the policy for how often the manual tests should be run (see #2 for ideas). You should then add a Wiki page for each test, describing the starting condition (often called the precondition) for each test, the steps taken in the test, and the expected ending state of the system. The precondition gives you an opportunity to state where a test begins and what should be true when it starts, e.g., a user has already logged in and placed two items into the shopping cart. This way each test does not have to start from the very beginning of the system (if each test starts with "the user creates an account" or "the user logs in", this is redundant and should be removed, tests should focus on specific usage scenarios, features, and requirements). The steps taken should be detailed, with clear, specific data provided at each step, and with clear instructions that allow the tester to know if a step succeeded or failed (don't say "enter last name", say "enter Smith", and don't say "the step succeeds", but say "a banner message displays stating "User account Smith created"). The expected ending state should summarize the new state of the system in a way that can be checked -- a new user is added to the database, a new message has been sent, a specific game state has been reached, or the specific file has been uploaded to a specific directory, for instance.

**Comment by sofireSophia** [comment]
@ZabeRauf please document testing adding an event to a calendar, @PatrickLanning please document testing user registration, logging in, and the nav bar. I will document testing adding a recipe.

**Comment by ZabeRauf** [comment]
YES SQUAAAD LEADER

**Comment by ZabeRauf** [comment]
Documenting is done Squad leaderrrrr. Let me know if more should be done.
